name: Build source and binary packages

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo
      - name: Install APT dependencies
        run: sudo apt install build-essential devscripts debhelper equivs
      - name: Build Debian package
        run: make debian
        working-directory: repo
      - uses: actions/upload-artifact@v2
        with:
          name: debian
          path: |
            *.deb
            *.dsc
            *.changes
            *.tar.*
            *.buildinfo
            *.build